// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package filesafe

import(
	"bytes"
	"context"
	"reflect"
	"database/sql/driver"
	"errors"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

type StatusCode int64
const (
  StatusCode_SUCCESS StatusCode = 0
  StatusCode_EXCEPTION StatusCode = 1
)

func (p StatusCode) String() string {
  switch p {
  case StatusCode_SUCCESS: return "SUCCESS"
  case StatusCode_EXCEPTION: return "EXCEPTION"
  }
  return "<UNSET>"
}

func StatusCodeFromString(s string) (StatusCode, error) {
  switch s {
  case "SUCCESS": return StatusCode_SUCCESS, nil 
  case "EXCEPTION": return StatusCode_EXCEPTION, nil 
  }
  return StatusCode(0), fmt.Errorf("not a valid StatusCode string")
}


func StatusCodePtr(v StatusCode) *StatusCode { return &v }

func (p StatusCode) MarshalText() ([]byte, error) {
return []byte(p.String()), nil
}

func (p *StatusCode) UnmarshalText(text []byte) error {
q, err := StatusCodeFromString(string(text))
if (err != nil) {
return err
}
*p = q
return nil
}

func (p *StatusCode) Scan(value interface{}) error {
v, ok := value.(int64)
if !ok {
return errors.New("Scan value is not int64")
}
*p = StatusCode(v)
return nil
}

func (p * StatusCode) Value() (driver.Value, error) {
  if p == nil {
    return nil, nil
  }
return int64(*p), nil
}
