/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package filesafe;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SearchFileRes implements org.apache.thrift.TBase<SearchFileRes, SearchFileRes._Fields>, java.io.Serializable, Cloneable, Comparable<SearchFileRes> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SearchFileRes");

  private static final org.apache.thrift.protocol.TField STATUS_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("status_code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField FILE_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("file_list", org.apache.thrift.protocol.TType.STRING, (short)10);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SearchFileResStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SearchFileResTupleSchemeFactory();

  /**
   * 
   * @see StatusCode
   */
  public @org.apache.thrift.annotation.Nullable StatusCode status_code; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String message; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String file_list; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see StatusCode
     */
    STATUS_CODE((short)1, "status_code"),
    MESSAGE((short)2, "message"),
    FILE_LIST((short)10, "file_list");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS_CODE
          return STATUS_CODE;
        case 2: // MESSAGE
          return MESSAGE;
        case 10: // FILE_LIST
          return FILE_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS_CODE, new org.apache.thrift.meta_data.FieldMetaData("status_code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, StatusCode.class)));
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FILE_LIST, new org.apache.thrift.meta_data.FieldMetaData("file_list", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "JsonString")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SearchFileRes.class, metaDataMap);
  }

  public SearchFileRes() {
  }

  public SearchFileRes(
    StatusCode status_code,
    java.lang.String message,
    java.lang.String file_list)
  {
    this();
    this.status_code = status_code;
    this.message = message;
    this.file_list = file_list;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SearchFileRes(SearchFileRes other) {
    if (other.isSetStatus_code()) {
      this.status_code = other.status_code;
    }
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    if (other.isSetFile_list()) {
      this.file_list = other.file_list;
    }
  }

  public SearchFileRes deepCopy() {
    return new SearchFileRes(this);
  }

  @Override
  public void clear() {
    this.status_code = null;
    this.message = null;
    this.file_list = null;
  }

  /**
   * 
   * @see StatusCode
   */
  @org.apache.thrift.annotation.Nullable
  public StatusCode getStatus_code() {
    return this.status_code;
  }

  /**
   * 
   * @see StatusCode
   */
  public SearchFileRes setStatus_code(@org.apache.thrift.annotation.Nullable StatusCode status_code) {
    this.status_code = status_code;
    return this;
  }

  public void unsetStatus_code() {
    this.status_code = null;
  }

  /** Returns true if field status_code is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus_code() {
    return this.status_code != null;
  }

  public void setStatus_codeIsSet(boolean value) {
    if (!value) {
      this.status_code = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMessage() {
    return this.message;
  }

  public SearchFileRes setMessage(@org.apache.thrift.annotation.Nullable java.lang.String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getFile_list() {
    return this.file_list;
  }

  public SearchFileRes setFile_list(@org.apache.thrift.annotation.Nullable java.lang.String file_list) {
    this.file_list = file_list;
    return this;
  }

  public void unsetFile_list() {
    this.file_list = null;
  }

  /** Returns true if field file_list is set (has been assigned a value) and false otherwise */
  public boolean isSetFile_list() {
    return this.file_list != null;
  }

  public void setFile_listIsSet(boolean value) {
    if (!value) {
      this.file_list = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case STATUS_CODE:
      if (value == null) {
        unsetStatus_code();
      } else {
        setStatus_code((StatusCode)value);
      }
      break;

    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((java.lang.String)value);
      }
      break;

    case FILE_LIST:
      if (value == null) {
        unsetFile_list();
      } else {
        setFile_list((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS_CODE:
      return getStatus_code();

    case MESSAGE:
      return getMessage();

    case FILE_LIST:
      return getFile_list();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case STATUS_CODE:
      return isSetStatus_code();
    case MESSAGE:
      return isSetMessage();
    case FILE_LIST:
      return isSetFile_list();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SearchFileRes)
      return this.equals((SearchFileRes)that);
    return false;
  }

  public boolean equals(SearchFileRes that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_status_code = true && this.isSetStatus_code();
    boolean that_present_status_code = true && that.isSetStatus_code();
    if (this_present_status_code || that_present_status_code) {
      if (!(this_present_status_code && that_present_status_code))
        return false;
      if (!this.status_code.equals(that.status_code))
        return false;
    }

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_file_list = true && this.isSetFile_list();
    boolean that_present_file_list = true && that.isSetFile_list();
    if (this_present_file_list || that_present_file_list) {
      if (!(this_present_file_list && that_present_file_list))
        return false;
      if (!this.file_list.equals(that.file_list))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetStatus_code()) ? 131071 : 524287);
    if (isSetStatus_code())
      hashCode = hashCode * 8191 + status_code.getValue();

    hashCode = hashCode * 8191 + ((isSetMessage()) ? 131071 : 524287);
    if (isSetMessage())
      hashCode = hashCode * 8191 + message.hashCode();

    hashCode = hashCode * 8191 + ((isSetFile_list()) ? 131071 : 524287);
    if (isSetFile_list())
      hashCode = hashCode * 8191 + file_list.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SearchFileRes other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetStatus_code(), other.isSetStatus_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status_code, other.status_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMessage(), other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFile_list(), other.isSetFile_list());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFile_list()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.file_list, other.file_list);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SearchFileRes(");
    boolean first = true;

    sb.append("status_code:");
    if (this.status_code == null) {
      sb.append("null");
    } else {
      sb.append(this.status_code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("message:");
    if (this.message == null) {
      sb.append("null");
    } else {
      sb.append(this.message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("file_list:");
    if (this.file_list == null) {
      sb.append("null");
    } else {
      sb.append(this.file_list);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SearchFileResStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SearchFileResStandardScheme getScheme() {
      return new SearchFileResStandardScheme();
    }
  }

  private static class SearchFileResStandardScheme extends org.apache.thrift.scheme.StandardScheme<SearchFileRes> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SearchFileRes struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status_code = filesafe.StatusCode.findByValue(iprot.readI32());
              struct.setStatus_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // FILE_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.file_list = iprot.readString();
              struct.setFile_listIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SearchFileRes struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.status_code != null) {
        oprot.writeFieldBegin(STATUS_CODE_FIELD_DESC);
        oprot.writeI32(struct.status_code.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.message);
        oprot.writeFieldEnd();
      }
      if (struct.file_list != null) {
        oprot.writeFieldBegin(FILE_LIST_FIELD_DESC);
        oprot.writeString(struct.file_list);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SearchFileResTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SearchFileResTupleScheme getScheme() {
      return new SearchFileResTupleScheme();
    }
  }

  private static class SearchFileResTupleScheme extends org.apache.thrift.scheme.TupleScheme<SearchFileRes> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SearchFileRes struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetStatus_code()) {
        optionals.set(0);
      }
      if (struct.isSetMessage()) {
        optionals.set(1);
      }
      if (struct.isSetFile_list()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetStatus_code()) {
        oprot.writeI32(struct.status_code.getValue());
      }
      if (struct.isSetMessage()) {
        oprot.writeString(struct.message);
      }
      if (struct.isSetFile_list()) {
        oprot.writeString(struct.file_list);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SearchFileRes struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.status_code = filesafe.StatusCode.findByValue(iprot.readI32());
        struct.setStatus_codeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.message = iprot.readString();
        struct.setMessageIsSet(true);
      }
      if (incoming.get(2)) {
        struct.file_list = iprot.readString();
        struct.setFile_listIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

