/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package filesafe;


public enum StatusCode implements org.apache.thrift.TEnum {
  SUCCESS(0),
  EXCEPTION(1);

  private final int value;

  private StatusCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static StatusCode findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case 1:
        return EXCEPTION;
      default:
        return null;
    }
  }
}
